version: '3'
services:
    action_server:
      container_name: "action_server"
      build:
        context: ./actions
      volumes:
        - ./actions:/app/actions
        - ./data:/app/data
      ports:
        - "5055:5055"

    rasa_core:
      container_name: "rasa_core"
      user: root
      build:
        context:  .
      volumes:
      - ./:/app
      ports:
        - "5005:5005"
      depends_on:
        - action_server
    fastapi:
      build:
        context: ./web_server
      ports:
        - "8004:8000"
      depends_on:
        - rasa_core
      logging:
       options:
        max-size: "50m"
        max-file: "3"
    vk_api:
      build:
        context: ./vk
      depends_on:
        - rasa_core
        - fastapi